apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-node
  labels:
    name: redis-node
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: redis-node
    spec:
      containers:
      - name: redis-node
        image: redis
        imagePullPolicy: Always
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
