apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twemproxy
  labels:
    name: twemproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: twemproxy
    spec:
      containers:
      - name: twemproxy
        image: tkporter/twemproxy:latest
        imagePullPolicy: Always
        ports:
        - name: twemproxy
          containerPort: 22121
